### ISSUE TITLE
Bot not running?

### ISSUE THREAD

**Issue by nickretallack** [ASzc/telegram-rcv-bot#1]
I talked to @RankedPollBot on telegram but it didn't respond.

**Comment by ASzc** [comment]
Hi. It is indeed not running. The original purpose I wrote it for is no longer a concern, and I didn't want to pay for and maintain that VPS anymore. I checked the database before I shut it down, and I couldn't see any recent use of the bot.

Telegram does do a limited form of [multi-answer poll](https://telegram.org/blog/polls-2-0-vmq) now.

I've deleted the bot from BotFather, so if anyone wants to run this source code with the same username on telegram, they should be free to do so.

**Comment by nickretallack** [comment]
Thank you.  I'd like to figure out how to run it.
