### ISSUE TITLE
Bots down, can't seem to my my own deployment work.

### ISSUE THREAD

**Issue by MilkManEX** [ASzc/telegram-rcv-bot#2]
As title, looks like it's been abandoned. Deploying it myself has proven to be a problem.

**Comment by ASzc** [comment]
Yeah, see #1.

I shut it down partly due to inactivity, but now people seem to want it? I'll consider starting it up again.

Were you a user beforehand, or just found it now through Google?

**Comment by MilkManEX** [comment]
Just google. Had only just thought to see if any ranked-choice bots existed, but it seems they're all defunct now.

**Comment by nickretallack** [comment]
I found this while I was trying to figure out how to make such a bot.  Ranked choice voting is important and I want to raise awareness of it by using it often in normal life.

**Comment by ASzc** [comment]
Ok, I have it back running under the same RankedPollBot username
