### ISSUE TITLE
Something broke

### ISSUE THREAD

**Issue by MilkManEX** [ASzc/telegram-rcv-bot#3]
![image](https://user-images.githubusercontent.com/16171167/95591010-c2dfc280-0a14-11eb-99b1-565bb9e9b6b4.png)

Been sending this every minute since yesterday and is unresponsive otherwise. Poll completed and it never sent results.

**Comment by ASzc** [comment]
I think you stopped a poll without any results maybe? Will try to fix it

**Comment by ASzc** [comment]
I think that fixed it, reopen if not

**Comment by MilkManEX** [comment]
Test poll not generating results.

![image](https://user-images.githubusercontent.com/16171167/95602182-8915b880-0a22-11eb-8d84-24fac7188b83.png)

![image](https://user-images.githubusercontent.com/16171167/95602069-684d6300-0a22-11eb-929f-724425a8e976.png)

I imagine this is why it was crashing with no results, since it wasn't recording them.

**Comment by ASzc** [comment]
Closing to move this results issue to #4
